# fly.toml app configuration file generated for hbot on 2023-06-30T21:47:22+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hbot"
primary_region = "hkg"
kill_signal = "SIGINT"
kill_timeout = "5s"
